-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.features
(
    id serial NOT NULL,
    product_id integer,
    feature character varying(50),
    value character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    name character varying(50),
    slogan character varying(150),
    description character varying(300),
    category character varying(50),
    default_price money,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.sku
(
    id serial NOT NULL,
    style_id integer,
    size character varying(50),
    quantity integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.photos
(
    id serial NOT NULL,
    style_id integer,
    url text,
    thumbnail_url text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.styles
(
    style_id serial NOT NULL,
    product_id integer,
    name character varying(50),
    sale_price money,
    original_price money,
    default_style boolean,
    PRIMARY KEY (style_id)
);

CREATE TABLE IF NOT EXISTS public.related
(
    id serial NOT NULL,
    product_id integer,
    related_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE public.features
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id)
    NOT VALID;


ALTER TABLE public.styles
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (style_id)
    REFERENCES public.styles (style_id)
    NOT VALID;


ALTER TABLE public.sku
    ADD FOREIGN KEY (style_id)
    REFERENCES public.styles (style_id)
    NOT VALID;


ALTER TABLE public.related
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id)
    NOT VALID;

END;